### ISSUE TITLE
Approval of users 

### ISSUE THREAD

**Issue by cute-poison** [yungifez/skuul#359] opened 2023-10-12 16:41 UTC
The approval of users isn't giving options to accept or reject users or applicants

**Comment by yungifez** [comment] 2023-10-12 17:01
Haha like I said

I can't fix the bug

No pc🤣🤣

**Comment by cute-poison** [comment] 2023-10-12 17:04
It's sad 😭 is there anyway you can guide me towards fixing it please it
will really be of help that is what is keeping me from completion

**Comment by yungifez** [comment] 2023-10-13 00:57
Haha I don't know what the problem is for now

**Comment by yungifez** [comment] 2023-10-13 02:46
Try changing the line

`        $this->statuses = $this->applicant->accountApplication->statuses()->get();`

To this

`        $this->statuses = $this->applicant->accountApplication->getAllStatuses();`



I'm not sure

**Comment by cute-poison** [comment] 2023-10-13 10:40
Couldn't find the file
Where is inserted could you help me out  $this->statuses =
$this->applicant->accountApplication->statuses()->get();

**Comment by cute-poison** [comment] 2023-10-15 21:01
Please any update on your system

**Comment by yungifez** [comment] 2023-10-16 00:07
My PC is still damaged sorry

**Comment by yungifez** [comment] 2023-11-21 02:09
Fixed in #261

**Closed by yungifez** 2023-11-21 02:09 UTC
